Repository Skyvern-AI/skyvern, pull requests merged in 2025-08, with the labels that each got.

#3076 add more rule to parse filename when downloading
  skyvern/forge/sdk/api/files.py
Labels: sync, LawyZheng

#3075 create_project + update/deploy_project
  skyvern/forge/sdk/artifact/manager.py
  skyvern/forge/sdk/artifact/models.py
  skyvern/forge/sdk/artifact/storage/base.py
  skyvern/forge/sdk/artifact/storage/local.py
  skyvern/forge/sdk/artifact/storage/s3.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/routes/__init__.py
  skyvern/forge/sdk/routes/projects.py
  skyvern/schemas/peojects.py
  skyvern/schemas/projects.py
  skyvern/services/project_service.py
Labels: sync, wintonzheng

#3095 fix dom listener bug
  skyvern/webeye/scraper/domUtils.js
Labels: sync, LawyZheng

#3098 Jon/sky 5452 sidebar improvements
  skyvern-frontend/src/components/NavLinkGroup.tsx
  skyvern-frontend/src/hooks/useIsMobile.ts
  skyvern-frontend/src/routes/root/NavigationHamburgerMenu.tsx
  skyvern-frontend/src/routes/root/SidebarContent.tsx
Labels: sync, jomido

#3100 return `None` from db layer if no persistent browser session is found (rather than raising an error)
  skyvern/forge/sdk/db/client.py
Labels: sync, jomido

#3101 set status to failed when browser session fails to initially connect
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/schemas/persistent_browser_sessions.py
  skyvern/webeye/persistent_sessions_manager.py
Labels: sync, jomido

#3103 select agent supports inputting secrete
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3104 feat: encrypt org auth tokens with AES
  alembic/versions/2025_08_05_0432-dd29417b397c_add_encrypt_token_and_method.py
  skyvern/config.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/encrypt/__init__.py
  skyvern/forge/sdk/encrypt/aes.py
  skyvern/forge/sdk/encrypt/base.py
Labels: sync, wintonzheng

#3111 fix creating org token encryption issue
  skyvern/forge/sdk/services/org_auth_token_service.py
Labels: sync, LawyZheng

#3113 elide duration from workflow blocks in timeline
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunTimelineBlockItem.tsx
Labels: sync, jomido

#3114 do not clear input when empty
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3118 workflows GET fix
  skyvern/forge/sdk/db/utils.py
Labels: sync, jomido

#3120 Jon/sky 5803 create workflow scripts table
  alembic/versions/2025_08_06_1946-2fe3e908a028_add_workflow_scripts_table.py
  skyvern/forge/sdk/db/id.py
  skyvern/forge/sdk/db/models.py
Labels: sync, jomido

#3126 support uri format otp secrete
  skyvern/exceptions.py
  skyvern/forge/sdk/services/bitwarden.py
  skyvern/forge/sdk/services/credentials.py
  skyvern/forge/sdk/workflow/context_manager.py
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3127 fix valid opt secret detect
  skyvern/forge/sdk/services/credentials.py
Labels: sync, LawyZheng

#3129 add finished_at to steps table
  alembic/versions/2025_08_07_1530-d67d7c00ab02_add_finished_at_to_steps_table.py
  skyvern/forge/sdk/db/models.py
Labels: sync, jomido

#3131 add cache key input to workflow settings
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowDebugger.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowEditor.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/types.ts
  skyvern-frontend/src/routes/workflows/editor/workflowEditorUtils.ts
  skyvern-frontend/src/routes/workflows/types/workflowTypes.ts
  skyvern-frontend/src/routes/workflows/types/workflowYamlTypes.ts
Labels: sync, jomido

#3132 always return debug sessions that are <30s fresh
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/schemas/scripts.py
Labels: sync, jomido

#3135 write finished_at to steps table
  skyvern/forge/sdk/db/client.py
Labels: sync, jomido

#3139 set-initial-window-debugger-position-size-as-specified-in-the
  skyvern-frontend/src/components/FloatingWindow.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowDebugger.tsx
Labels: sync, jomido

#3145 Rework Workflow Save
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowDebugger.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowEditor.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/components/NodeHeader.tsx
  skyvern-frontend/src/store/WorkflowHasChangesStore.ts
Labels: sync, jomido

#3151 workflow script creation
  skyvern/core/code_generations/generate_code.py
  skyvern/core/code_generations/transform_workflow_run.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, wintonzheng

#3157 Script generation
  skyvern/__init__.py
  skyvern/core/code_generations/workflow_wrappers.py
  skyvern/core/script_generations/__init__.py
  skyvern/core/script_generations/generate_script.py
  skyvern/core/script_generations/run_initializer.py
  skyvern/core/script_generations/script_run_context_manager.py
  skyvern/core/script_generations/skyvern_page.py
  skyvern/core/script_generations/transform_workflow_run.py
  skyvern/core/script_generations/workflow_wrappers.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/routes/scripts.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/services/script_service.py
  skyvern/webeye/actions/action_types.py
  skyvern/webeye/actions/handler.py
  skyvern/webeye/actions/handler_utils.py
Labels: sync, wintonzheng

#3163 fix download file name bug
  skyvern/forge/sdk/api/files.py
Labels: sync, LawyZheng

#3172 fix file type detect bug
  skyvern/forge/sdk/routes/credentials.py
  skyvern/forge/sdk/workflow/models/block.py
Labels: sync, LawyZheng

#3175 Jon/workspace
  skyvern-frontend/src/components/FloatingWindow.tsx
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowDebugger.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowEditor.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/components/NodeHeader.tsx
  skyvern-frontend/src/routes/workflows/editor/panels/WorkflowNodeLibraryPanel.tsx
  skyvern-frontend/src/routes/workflows/editor/panels/WorkflowParametersPanel.tsx
  skyvern-frontend/src/routes/workflows/hooks/useRanker.ts
Labels: sync, jomido

#3179 make other script enabled blocks flip-to-script; add type-checked lis…
  skyvern-frontend/src/routes/workflows/editor/nodes/ActionNode/ActionNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ExtractionNode/ExtractionNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileDownloadNode/FileDownloadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/LoginNode/LoginNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/NodeActionMenu.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/TaskNode/TaskNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/URLNode/URLNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ValidationNode/ValidationNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/components/NodeHeader.tsx
  skyvern-frontend/src/routes/workflows/types/workflowTypes.ts
Labels: sync, jomido

#3184 optimize scraping part 1
  skyvern/webeye/scraper/domUtils.js
Labels: sync, LawyZheng

#3185 optimize scraping part 2
  skyvern/webeye/scraper/domUtils.js
Labels: sync, LawyZheng

#3191 stop building element tree again and again when drawing boudingbox
  skyvern/webeye/scraper/domUtils.js
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#3195 remove hard waiting time in scraping
  skyvern/exceptions.py
  skyvern/webeye/scraper/scraper.py
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#3196 allow deletion of blocks within the debugger
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/components/NodeHeader.tsx
Labels: sync, jomido

#3197 fix stop waiting bug
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/components/NodeHeader.tsx
  skyvern/webeye/scraper/scraper.py
Labels: sync, LawyZheng

#3201 fix wait for animation end
  skyvern/webeye/scraper/domUtils.js
  skyvern/webeye/scraper/scraper.py
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#3202 Jon/sky 5906 debugger show actions inputs outputs for a block run
  skyvern-frontend/src/api/types.ts
  skyvern-frontend/src/components/Timer.tsx
  skyvern-frontend/src/router.tsx
  skyvern-frontend/src/routes/workflows/debugger/Debugger.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerPostRunParameters.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerRun.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerRunOutput.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerRunTimeline.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerSendEmailBlockInfo.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerTaskBlockParameters.tsx
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ActionNode/ActionNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/CodeBlockNode/CodeBlockNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/DownloadNode/DownloadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ExtractionNode/ExtractionNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileDownloadNode/FileDownloadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileParserNode/FileParserNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileUploadNode/FileUploadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/LoginNode/LoginNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/LoopNode/LoopNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/NavigationNode/NavigationNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/PDFParserNode/PDFParserNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/SendEmailNode/SendEmailNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/TaskNode/TaskNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/Taskv2Node/Taskv2Node.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/TextPromptNode/TextPromptNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/URLNode/URLNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/UploadNode/UploadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ValidationNode/ValidationNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/WaitNode/WaitNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/components/NodeHeader.tsx
Labels: sync, jomido

#3203 fix accordion rebder bug from flippable component
  skyvern-frontend/src/hooks/useRerender.ts
  skyvern-frontend/src/routes/workflows/editor/nodes/ActionNode/ActionNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ExtractionNode/ExtractionNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileDownloadNode/FileDownloadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/HttpRequestNode/HttpRequestNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/LoginNode/LoginNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/NavigationNode/NavigationNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/TaskNode/TaskNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/Taskv2Node/Taskv2Node.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ValidationNode/ValidationNode.tsx
Labels: sync, jomido

#3208 Jon/sky 5841 make debug view the default view
  skyvern-frontend/src/components/FloatingWindow.tsx
  skyvern-frontend/src/components/icons/BrowserIcon.tsx
  skyvern-frontend/src/routes/discover/WorkflowTemplates.tsx
  skyvern-frontend/src/routes/workflows/ImportWorkflowButton.tsx
  skyvern-frontend/src/routes/workflows/WorkflowPage.tsx
  skyvern-frontend/src/routes/workflows/WorkflowRun.tsx
  skyvern-frontend/src/routes/workflows/Workflows.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerRunTimeline.tsx
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ActionNode/ActionNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/CodeBlockNode/CodeBlockNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/DownloadNode/DownloadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ExtractionNode/ExtractionNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileDownloadNode/FileDownloadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileParserNode/FileParserNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileUploadNode/FileUploadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/LoginNode/LoginNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/LoopNode/LoopNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/NavigationNode/NavigationNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/PDFParserNode/PDFParserNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/SendEmailNode/SendEmailNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/TaskNode/TaskNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/Taskv2Node/Taskv2Node.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/TextPromptNode/TextPromptNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/URLNode/URLNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/UploadNode/UploadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/ValidationNode/ValidationNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/WaitNode/WaitNode.tsx
  skyvern-frontend/src/routes/workflows/editor/panels/WorkflowNodeLibraryPanel.tsx
  skyvern-frontend/src/routes/workflows/hooks/useCreateWorkflowMutation.ts
Labels: sync, jomido

#3210 decrease parse input prompt token
  skyvern/webeye/actions/handler.py
  skyvern/webeye/scraper/scraper.py
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#3213 react-flow updates: allow one in current render cycle; defer rest to …
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
Labels: sync, jomido

#3216 script generation improvement
  skyvern/__init__.py
  skyvern/config.py
  skyvern/constants.py
  skyvern/core/script_generations/constants.py
  skyvern/core/script_generations/generate_script.py
  skyvern/core/script_generations/run_initializer.py
  skyvern/core/script_generations/script_run_context_manager.py
  skyvern/core/script_generations/skyvern_page.py
  skyvern/core/script_generations/transform_workflow_run.py
  skyvern/core/script_generations/workflow_wrappers.py
  skyvern/forge/app.py
  skyvern/forge/prompts/skyvern/script-generation-input-text-generatiion.j2
  skyvern/forge/sdk/workflow/service.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3217 add gpt5 model option
  skyvern/config.py
Labels: sync, wintonzheng

#3226 add control buttons to debugger; change 'cede control' text
  skyvern-frontend/src/components/BrowserStream.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3229 remove hard wait time in input action
  skyvern/webeye/actions/handler.py
  skyvern/webeye/scraper/domUtils.js
Labels: sync, LawyZheng

#3232 make WorkflowBlockInputArea a 'hybrid sync component', rather than a …
  skyvern-frontend/src/components/WorkflowBlockInputTextarea.tsx
Labels: sync, jomido

#3234 run script with workflow block run, task, step and artifacts built
  skyvern/core/script_generations/generate_script.py
  skyvern/core/script_generations/skyvern_page.py
  skyvern/forge/agent.py
  skyvern/forge/sdk/core/skyvern_context.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3235 post action screenshot works for script run
  skyvern/core/script_generations/skyvern_page.py
  skyvern/webeye/browser_manager.py
Labels: sync, wintonzheng

#3237 start build tree from HTML element
  skyvern/webeye/scraper/domUtils.js
Labels: sync, LawyZheng

#3238 script gen: extract action support
  skyvern/config.py
  skyvern/core/script_generations/generate_script.py
  skyvern/core/script_generations/skyvern_page.py
  skyvern/forge/app.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3239 use dynamic waiting for select action
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3243 Jon/sky 5981 turn off debugger for oss and self host
  skyvern-frontend/src/router.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3244 support cdp for task and workflow
  alembic/versions/2025_08_21_0313-afdfd14ac46d_add_cdp_address_in_task_and_workflow.py
  skyvern/forge/agent.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/executor/async_executor.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/schemas/task_v2.py
  skyvern/forge/sdk/schemas/tasks.py
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/runs.py
  skyvern/services/task_v2_service.py
  skyvern/services/workflow_service.py
  skyvern/webeye/browser_factory.py
  skyvern/webeye/browser_manager.py
Labels: sync, LawyZheng

#3246 support input date
  skyvern/forge/prompts/skyvern/check-date-format.j2
  skyvern/utils/prompt_engine.py
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3263 shorten random string for secret value
  skyvern/forge/sdk/workflow/context_manager.py
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/services/task_v2_service.py
  skyvern/utils/strings.py
Labels: sync, LawyZheng

#3264 generate GeneratedWorkflowParameters
  skyvern/__init__.py
  skyvern/core/script_generations/generate_script.py
  skyvern/core/script_generations/generate_workflow_parameters.py
  skyvern/core/script_generations/run_initializer.py
  skyvern/core/script_generations/skyvern_page.py
  skyvern/forge/prompts/skyvern/generate-workflow-parameters.j2
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3272 no success (or fail) for action list/action card
  skyvern-frontend/src/routes/tasks/detail/ScrollableActionList.tsx
  skyvern-frontend/src/routes/workflows/workflowRun/ActionCard.tsx
Labels: sync, jomido

#3274 add icon for scripted actions
  skyvern-frontend/src/api/types.ts
  skyvern-frontend/src/routes/tasks/detail/ScrollableActionList.tsx
  skyvern-frontend/src/routes/tasks/detail/hooks/useActions.ts
  skyvern-frontend/src/routes/workflows/workflowRun/ActionCard.tsx
Labels: sync, jomido

#3277 GPT-5 Support + Better Logs
  skyvern/config.py
  skyvern/forge/sdk/api/llm/api_handler_factory.py
  skyvern/forge/sdk/api/llm/config_registry.py
Labels: sync, suchintan

#3278 make missing script key value 'default'
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern-frontend/src/routes/workflows/editor/panels/WorkflowCacheKeyValuesPanel.tsx
  skyvern-frontend/src/store/WorkflowHasChangesStore.ts
Labels: sync, jomido

#3283 store workflow start block code
  skyvern/config.py
  skyvern/core/script_generations/generate_script.py
Labels: sync, wintonzheng

#3285 script skyvern fallback
  skyvern/forge/agent.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/models.py
  skyvern/schemas/steps.py
  skyvern/services/script_service.py
  skyvern/webeye/actions/models.py
Labels: sync, wintonzheng

#3287 More logs to show why a script fails
  skyvern/core/script_generations/skyvern_page.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3290 fix single input agent llm handler
  skyvern/forge/app.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3291 support select llm for file parser
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, LawyZheng

#3296 Action UI Update
  skyvern-frontend/src/routes/tasks/detail/ScrollableActionList.tsx
  skyvern-frontend/src/routes/workflows/workflowRun/ActionCard.tsx
Labels: sync, jomido

#3297 put it back the way it was
  skyvern-frontend/src/routes/tasks/detail/ScrollableActionList.tsx
  skyvern-frontend/src/routes/workflows/workflowRun/ActionCard.tsx
Labels: sync, jomido

#3301 expand start block when code is flipped
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
Labels: sync, jomido

#3302 redo 6035 because of 6036, which undid 6035
  skyvern-frontend/src/components/BrowserStream.tsx
  skyvern-frontend/src/components/FloatingWindow.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3304 fix missing recording for task v2 block
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/routes/scripts.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, LawyZheng

#3307 allow Exception in code block
  skyvern/forge/sdk/workflow/models/block.py
Labels: sync, LawyZheng

#3309 support to parse dash in otp secret
  skyvern/forge/sdk/services/credentials.py
Labels: sync, LawyZheng

#3310 use single press instead of press sequentially
  skyvern/webeye/actions/handler_utils.py
  skyvern/webeye/utils/dom.py
Labels: sync, LawyZheng

#3312 Add run timeline endpoint
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/routes/code_samples.py
Labels: sync, suchintan

#3314 Debugger Continuity (BE)
  alembic/versions/2025_08_28_2356-f54bab75b1c4_add_block_runs_table.py
  skyvern/exceptions.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/executor/async_executor.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/schemas/debug_sessions.py
  skyvern/forge/sdk/workflow/context_manager.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/runs.py
  skyvern/services/block_service.py
  skyvern/services/workflow_service.py
Labels: sync, jomido

#3317 remove copy copy button from code dropdown
  skyvern-frontend/src/components/CopyButton.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
Labels: sync, jomido

#3321 allow ai_fallback to save
  skyvern/forge/sdk/workflow/service.py
Labels: sync, jomido

#3322 code cache icon button instead of dropdown
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
Labels: sync, jomido

#3330 script regeneration after ai fallback
  skyvern/core/script_generations/generate_script.py
  skyvern/core/script_generations/skyvern_page.py
  skyvern/forge/sdk/db/client.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng
