Repository Skyvern-AI/skyvern, pull requests merged in 2025-09, with the labels that each got.

#3335 Fix extraction prompt templating
  skyvern/core/script_generations/generate_script.py
  skyvern/core/script_generations/skyvern_page.py
  skyvern/core/script_generations/transform_workflow_run.py
  skyvern/forge/agent.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3338 downloaded file debugger accessible
  skyvern/exceptions.py
  skyvern/forge/agent.py
  skyvern/forge/sdk/api/aws.py
  skyvern/forge/sdk/api/files.py
  skyvern/forge/sdk/artifact/storage/base.py
  skyvern/forge/sdk/artifact/storage/local.py
  skyvern/forge/sdk/artifact/storage/s3.py
  skyvern/webeye/actions/handler.py
  skyvern/webeye/browser_factory.py
Labels: sync, LawyZheng

#3340 Jon/debugger layout
  skyvern-frontend/src/components/BrowserStream.tsx
  skyvern-frontend/src/components/FloatingWindow.tsx
  skyvern-frontend/src/components/Tip.tsx
  skyvern-frontend/src/components/browser-stream.css
  skyvern-frontend/src/routes/tasks/detail/ActionTypePillMinimal.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerRun.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerRunMinimal.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerRunTimeline.tsx
  skyvern-frontend/src/routes/workflows/debugger/DebuggerRunTimelineMinimal.tsx
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern-frontend/src/routes/workflows/editor/workspace-styles.css
  skyvern-frontend/src/routes/workflows/workflowRun/ActionCardMinimal.tsx
  skyvern-frontend/src/routes/workflows/workflowRun/ItemStatusIndicator.tsx
  skyvern-frontend/src/routes/workflows/workflowRun/ThoughtCardMinimal.tsx
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunTimelineBlockItemMinimal.tsx
Labels: sync, jomido

#3342 debugger layout fixes 2
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3347 improve credential input
  skyvern/forge/sdk/workflow/context_manager.py
Labels: sync, LawyZheng

#3348 fix extract action model
  skyvern/webeye/actions/actions.py
Labels: sync, LawyZheng

#3351 fix credential context bug
  skyvern/forge/sdk/workflow/context_manager.py
Labels: sync, LawyZheng

#3353 Jon/debugger layout fixes 3
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3355 support to use vaultwarden for skyvern credential
  skyvern/forge/sdk/services/bitwarden.py
Labels: sync, LawyZheng

#3358 accept ai_fallback for new workflows
  skyvern-frontend/src/routes/tasks/create/PromptBox.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/NodeActionMenu.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern/forge/sdk/workflow/service.py
Labels: sync, jomido

#3361 fix block screenshot bug
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#3362 fix input value bug for script run
  skyvern/core/script_generations/skyvern_page.py
Labels: sync, wintonzheng

#3363 enable ENABLE_CODE_BLOCK by default and disable it for production/staging
  skyvern/config.py
Labels: sync, wintonzheng

#3364 show input value before the value is interpretated into a real secret
  skyvern/config.py
  skyvern/core/script_generations/skyvern_page.py
Labels: sync, wintonzheng

#3366 add skyvern defined error code
  skyvern/errors/errors.py
  skyvern/forge/agent.py
  skyvern/forge/sdk/db/client.py
Labels: sync, LawyZheng

#3376 Pre-convo UI
  skyvern-frontend/src/components/Orgwalled.tsx
  skyvern-frontend/src/components/icons/BugIcon.tsx
  skyvern-frontend/src/components/icons/DebugIcon.tsx
  skyvern-frontend/src/routes/tasks/create/PromptBox.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/Taskv2Node/Taskv2Node.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/components/NodeHeader.tsx
  skyvern-frontend/src/routes/workflows/hooks/useCacheKeyValuesQuery.ts
  skyvern-frontend/src/store/useAutoplayStore.ts
Labels: sync, jomido

#3377 reduce complexity in Workspace
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3380 make ai fallback true by default
  skyvern-frontend/src/routes/workflows/Workflows.tsx
  skyvern-frontend/src/routes/workflows/debugger/Debugger.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowEditor.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern-frontend/src/routes/workflows/editor/workflowEditorUtils.ts
  skyvern-frontend/src/store/WorkflowHasChangesStore.ts
Labels: sync, jomido

#3381 update cache key value deletion verbiage
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3388 script video fix
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3391 retry bitwarden failed requests
  skyvern/forge/sdk/services/bitwarden.py
Labels: sync, LawyZheng

#3402 fix wrong endpoint error
  skyvern/forge/sdk/db/client.py
Labels: sync, LawyZheng

#3405 add dramatiq dependency
  poetry.lock
  pyproject.toml
Labels: sync, LawyZheng

#3428 add history to surface errorcode prompt
  skyvern/forge/agent.py
  skyvern/forge/prompts/skyvern/surface-user-defined-errors.j2
  skyvern/services/action_service.py
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3429 Use gemini 2_5 flash lite for create_extract_action
  skyvern/forge/agent.py
  skyvern/forge/sdk/api/llm/config_registry.py
  skyvern/webeye/actions/handler.py
Labels: sync, pedrohsdb

#3437 Script run - take screenshot for the workflow run block
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3444 Jon/sky 6395 refresh code while workflow is running
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern-frontend/src/routes/workflows/editor/utils.ts
  skyvern-frontend/src/routes/workflows/hooks/useBlockScriptsQuery.ts
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunCode.tsx
Labels: sync, jomido

#3445 Jon/sky 6375 alter how show all code works
  skyvern-frontend/src/components/Splitter.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern-frontend/src/routes/workflows/utils.ts
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunCode.tsx
Labels: sync, jomido

#3450 add status column to the workflow_scripts table
  alembic/versions/2025_09_17_1458-67add341e926_add_status_to_the_workflow_scripts_.py
  skyvern/forge/sdk/db/models.py
  skyvern/schemas/scripts.py
Labels: sync, wintonzheng

#3452 fix codeblock in debugger
  skyvern/forge/sdk/workflow/models/block.py
Labels: sync, LawyZheng

#3457 denpendent workflow run
  alembic/versions/2025_09_18_0529-8f208daee7d1_add_workflow_sequential_setting.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/workflows.py
Labels: sync, LawyZheng

#3459 fix cua bug
  skyvern/webeye/actions/handler.py
  skyvern/webeye/utils/dom.py
Labels: sync, LawyZheng

#3455 script gen - loop block support
  skyvern/__init__.py
  skyvern/core/script_generations/generate_script.py
  skyvern/core/script_generations/skyvern_page.py
  skyvern/core/script_generations/transform_workflow_run.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3464 Jon/improve cache key value deletion
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern/forge/sdk/routes/scripts.py
Labels: sync, jomido

#3466 remove slash from cache key value delete http call
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3468 use code/use ai in workflow run ui
  skyvern-frontend/src/routes/workflows/RunWorkflowForm.tsx
  skyvern-frontend/src/routes/workflows/editor/utils.ts
Labels: sync, jomido

#3479 Jon/hotfix always allow cache key edit
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
Labels: sync, jomido

#3483 default code gen to true for prompt-initiated workflows
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, jomido

#3485 hotfix via suchintan for some sort of unwanted increase of prompting
  skyvern/forge/agent_functions.py
Labels: sync, jomido

#3487 downloaded files in pbs response
  skyvern/forge/sdk/artifact/storage/base.py
  skyvern/forge/sdk/artifact/storage/local.py
  skyvern/forge/sdk/artifact/storage/s3.py
  skyvern/forge/sdk/routes/browser_sessions.py
  skyvern/webeye/schemas.py
Labels: sync, LawyZheng

#3489 generate_script will be used to run generated code
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
Labels: sync, wintonzheng

#3493 fix duplicated block library
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, wintonzheng

#3494 pass reasoning to error code gen
  skyvern/forge/prompts/skyvern/surface-user-defined-errors.j2
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3495 update to $0.05 per step both in frontend and backend
  skyvern/forge/sdk/workflow/service.py
Labels: sync, wintonzheng

#3496 sort pbs downloaded files
  skyvern/forge/sdk/artifact/storage/s3.py
  skyvern/forge/sdk/schemas/files.py
  skyvern/webeye/schemas.py
Labels: sync, LawyZheng

#3497 code caching: enabled/disabled UX for workflow run UI
  skyvern-frontend/src/components/AnimatedWave.tsx
  skyvern-frontend/src/components/SwitchBarNavigation.tsx
  skyvern-frontend/src/routes/workflows/WorkflowRun.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern-frontend/src/routes/workflows/hooks/useBlockScriptsQuery.ts
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunCode.tsx
  skyvern-frontend/src/store/UiStore.ts
Labels: sync, jomido

#3498 add ai_fallback to TaskV2Request model
  skyvern-frontend/src/components/AnimatedWave.tsx
  skyvern-frontend/src/components/SwitchBarNavigation.tsx
  skyvern-frontend/src/routes/workflows/WorkflowRun.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern-frontend/src/routes/workflows/hooks/useBlockScriptsQuery.ts
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunCode.tsx
  skyvern-frontend/src/store/UiStore.ts
  skyvern/forge/sdk/schemas/task_v2.py
Labels: sync, jomido

#3506 Add payload functionality to our experimentation framework
  skyvern/forge/sdk/experimentation/providers.py
Labels: sync, pedrohsdb

#3507 Dev scripts, Add support for rendering videos for browser sessions
  skyvern-frontend/src/routes/browserSession/BrowserSession.tsx
  skyvern-frontend/src/routes/browserSession/BrowserSessionVideo.tsx
Labels: sync, suchintan

#3508 aggregate error code in workflow run response
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, LawyZheng

#3510 do no surface error code for completion
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3512 public run endpoint with error code
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/runs.py
  skyvern/services/run_service.py
  skyvern/services/task_v2_service.py
  skyvern/services/workflow_service.py
Labels: sync, LawyZheng

#3515 Terminate WebSocket Stream when Session is Deleted
  skyvern-frontend/src/components/BrowserStream.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3520 Ensure scripts are freshly fetched for Workspace (they need to show up after a wf run)
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3521 workflow run UI: code generation affordances
  skyvern-frontend/src/components/SwitchBarNavigation.tsx
  skyvern-frontend/src/routes/workflows/WorkflowRun.tsx
  skyvern-frontend/src/routes/workflows/hooks/useBlockScriptsQuery.ts
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunCode.tsx
Labels: sync, jomido

#3524 remove valid css selector check
  skyvern/webeye/scraper/domUtils.js
Labels: sync, LawyZheng

#3531 Pedro/prompt caching
  skyvern/forge/agent.py
  skyvern/forge/prompts/skyvern/extract-action-dynamic.j2
  skyvern/forge/prompts/skyvern/extract-action-static.j2
  skyvern/forge/sdk/api/llm/api_handler_factory.py
  skyvern/forge/sdk/core/skyvern_context.py
Labels: sync, pedrohsdb

#3533 Fix unpacking error in build_and_record_step_prompt
  skyvern/forge/agent.py
Labels: sync, pedrohsdb

#3536 adding new gemini flash preview models
  skyvern/forge/sdk/api/llm/config_registry.py
Labels: sync, pedrohsdb

#3537 Add endpoint for browser sessions history
  skyvern/forge/sdk/api/llm/config_registry.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/routes/browser_sessions.py
Labels: sync, jomido

#3539 updating mypy
  poetry.lock
  pyproject.toml
Labels: sync, wintonzheng

#3540 Making ValidationBlock not count towards max_steps check
  skyvern/forge/sdk/workflow/service.py
Labels: sync, pedrohsdb

#3541 fix mypy issue for org tokens
  skyvern/cli/mcp.py
  skyvern/core/totp.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/routes/credentials.py
  skyvern/forge/sdk/workflow/context_manager.py
  skyvern/library/skyvern.py
  skyvern/services/task_v2_service.py
Labels: sync, wintonzheng

#3542 script gen - support skyvern.loop & cleaner interfaces for generated code (no need to pass context.parameters, implicit template rendering)
  skyvern/__init__.py
  skyvern/core/script_generations/generate_script.py
  skyvern/core/script_generations/run_initializer.py
  skyvern/core/script_generations/skyvern_page.py
  skyvern/forge/sdk/core/skyvern_context.py
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3543 fix workflow_run.run_with override
  skyvern/core/script_generations/skyvern_page.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, wintonzheng

#3552 hide versioning during workflow execution (or queueing)
  skyvern-frontend/src/routes/workflows/editor/WorkflowHeader.tsx
Labels: sync, jomido

#3557 Replace file_suffix with file_name (but keep vairable name for backwards compatibility), Add path to Azure Blob, remove defaulted {workflow_run_id}
  skyvern-frontend/src/routes/workflows/editor/helpContent.ts
  skyvern-frontend/src/routes/workflows/editor/nodes/ActionNode/ActionNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileDownloadNode/FileDownloadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileUploadNode/FileUploadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileUploadNode/types.ts
  skyvern-frontend/src/routes/workflows/editor/nodes/NavigationNode/NavigationNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/TaskNode/TaskNode.tsx
  skyvern/forge/agent.py
  skyvern/forge/sdk/workflow/context_manager.py
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/forge/sdk/workflow/models/parameter.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/workflows.py
  skyvern/services/task_v2_service.py
Labels: sync, suchintan

#3558 Handle duplicate files
  skyvern/forge/agent.py
Labels: sync, suchintan

#3563 reduce debug session browser session timeout minutes to 20
  skyvern/config.py
Labels: sync, jomido
