Repository Skyvern-AI/skyvern, pull requests merged in 2025-07, with the labels that each got.

#2849 extend select agent to support date picker
  skyvern/exceptions.py
  skyvern/forge/agent.py
  skyvern/services/task_v2_service.py
  skyvern/utils/prompt_engine.py
  skyvern/webeye/actions/handler.py
  skyvern/webeye/scraper/scraper.py
Labels: sync, LawyZheng

#2851 scroll back after screenshot
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#2878 implement an endpoint for running one or more labelled blocks in a workflow
  skyvern/exceptions.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/runs.py
  skyvern/services/block_service.py
  skyvern/services/workflow_service.py
Labels: sync, jomido

#2879 Jon/optimistic browser session id fetch
  skyvern-frontend/src/store/useOptimisticallyRequestBrowserSessionId.ts
Labels: sync, jomido

#2880 Enhance WorkflowNodeLibraryPanel with input focus management using useRef and useEffect for improved user experience
  skyvern-frontend/src/routes/workflows/editor/panels/WorkflowNodeLibraryPanel.tsx
  skyvern-frontend/src/store/useOptimisticallyRequestBrowserSessionId.ts
Labels: sync, Prakashmaheshwaran

#2887 laminar integration
  poetry.lock
  pyproject.toml
  skyvern/config.py
  skyvern/forge/agent.py
  skyvern/forge/agent_functions.py
  skyvern/forge/app.py
  skyvern/forge/sdk/api/llm/api_handler_factory.py
  skyvern/forge/sdk/trace/__init__.py
  skyvern/forge/sdk/trace/base.py
  skyvern/forge/sdk/trace/lmnr.py
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/services/task_v2_service.py
  skyvern/webeye/actions/handler.py
  skyvern/webeye/scraper/scraper.py
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#2897 add credentials to new axios client
  poetry.lock
  pyproject.toml
  skyvern-frontend/src/api/AxiosClient.ts
  skyvern/cli/run_commands.py
Labels: sync, jomido

#2892 APIKeyNotFound Exception
  skyvern/exceptions.py
Labels: sync, wintonzheng

#2902 add skyvern element check and uncheck
  skyvern/webeye/utils/dom.py
Labels: sync, LawyZheng

#2911 Jon/browser session view
  skyvern-frontend/src/components/BrowserStream.tsx
  skyvern-frontend/src/components/browser-stream.css
  skyvern-frontend/src/router.tsx
  skyvern-frontend/src/routes/browserSession/BrowserSession.tsx
Labels: sync, jomido

#2913 add pbs-based cancel endpoint for workflow runs
  skyvern/forge/sdk/routes/agent_protocol.py
Labels: sync, jomido

#2914 add browser session to debug store; use new cancel endpoint from #5450
  skyvern-frontend/src/routes/workflows/editor/nodes/components/NodeHeader.tsx
  skyvern-frontend/src/store/DebugStoreContext.tsx
Labels: sync, jomido

#2916 update run_task to make it possible to expose ecs task publicly
  skyvern/forge/sdk/api/aws.py
Labels: sync, wintonzheng

#2922 add session pool
  skyvern/schemas/browser_sessions.py
Labels: sync, LawyZheng

#2924 add a user hook; stubbed out for OSS-side; clerked out for cloud-side
  skyvern-frontend/src/App.tsx
  skyvern-frontend/src/api/types.ts
  skyvern-frontend/src/hooks/useUser.ts
  skyvern-frontend/src/store/UserContext.ts
Labels: sync, jomido

#2927 rewrite WS url more robustly
  skyvern-frontend/src/components/BrowserStream.tsx
  skyvern-frontend/src/routes/browserSession/BrowserSession.tsx
  skyvern-frontend/src/util/env.ts
Labels: sync, jomido

#2928 Jon/keyed browser session id cache
  skyvern-frontend/src/routes/workflows/editor/nodes/components/NodeHeader.tsx
  skyvern-frontend/src/store/DebugStoreContext.tsx
  skyvern-frontend/src/store/useOptimisticallyRequestBrowserSessionId.ts
Labels: sync, jomido

#2931 browser address schema update
  scripts/test_persistent_browsers.py
  skyvern/forge/sdk/routes/streaming_vnc.py
  skyvern/webeye/persistent_sessions_manager.py
Labels: sync, wintonzheng

#2936 add force textural element as interactable exp
  skyvern/config.py
  skyvern/webeye/scraper/domUtils.js
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#2939 fix sequential click agent bug
  skyvern/forge/prompts/skyvern/custom-select.j2
  skyvern/forge/prompts/skyvern/opened-dropdown-confirm.j2
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#2940 do not tirgger select loigc when trying to input search value
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#2943 componentize window; add buttons
  skyvern-frontend/src/components/FloatingWindow.tsx
Labels: sync, jomido

#2956 add maximized, and show[button] props
  skyvern-frontend/src/components/FloatingWindow.tsx
Labels: sync, jomido

#2957 add a splitter component (vertical/horizontal)
  skyvern-frontend/src/components/Splitter.tsx
Labels: sync, jomido

#2959 update Splitter component
  skyvern-frontend/src/components/Splitter.tsx
Labels: sync, jomido

#2961 re-reorder blocks in lib panel
  skyvern-frontend/src/routes/workflows/editor/panels/WorkflowNodeLibraryPanel.tsx
Labels: sync, jomido

#2965 no user-select when splitter is dragging
  skyvern-frontend/src/components/Splitter.tsx
  skyvern-frontend/src/index.css
Labels: sync, jomido

#2969 ensure browser session id for GET workflow run
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, jomido

#2973 dns for browser session（part 2)
  skyvern/forge/sdk/routes/streaming_vnc.py
  skyvern/forge/sdk/schemas/persistent_browser_sessions.py
Labels: sync, LawyZheng

#2974 dns for browser session (part 3)
  skyvern/forge/sdk/routes/streaming_vnc.py
Labels: sync, LawyZheng

#2976 remove unused func from webeye persistent sessions manager
  skyvern/webeye/persistent_sessions_manager.py
Labels: sync, jomido

#2977 distinctify failed scrapes due to no url
  skyvern/exceptions.py
  skyvern/forge/agent.py
  skyvern/webeye/scraper/scraper.py
Labels: sync, jomido

#2979 fix prompt
  skyvern/forge/prompts/skyvern/extract-action.j2
  skyvern/forge/prompts/skyvern/single-input-action.j2
Labels: sync, LawyZheng

#2984 allow empty urls
  skyvern/webeye/scraper/scraper.py
Labels: sync, jomido

#2988 normalize scroll for debugger and editor
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
Labels: sync, jomido

#2989 add take control/cede control buttons to browser stream view; improve branding yar
  skyvern-frontend/src/components/BrowserStream.tsx
  skyvern-frontend/src/components/browser-stream.css
  skyvern-frontend/src/routes/browserSession/BrowserSession.tsx
Labels: sync, jomido

#2991 make scraping timeout configurable
  skyvern/config.py
  skyvern/constants.py
  skyvern/webeye/scraper/scraper.py
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#2999 Login endpoint Part 2 - support 3 types of credentials and fix bugs
  skyvern/forge/sdk/routes/run_blocks.py
  skyvern/schemas/run_blocks.py
Labels: sync, wintonzheng

#3010 extend auto completion agent logic
  skyvern/forge/prompts/skyvern/auto-completion-choose-option.j2
  skyvern/forge/sdk/db/polls.py
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3011 use seperated userr goal check for sequential click agent
  skyvern/forge/prompts/skyvern/check-user-goal.j2
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3013 do not remove target attr
  skyvern/webeye/utils/dom.py
Labels: sync, LawyZheng

#3022 bump max session timeout to 4 hours
  skyvern/schemas/browser_sessions.py
Labels: sync, wintonzheng

#3029 fix style map parsing
  skyvern/webeye/scraper/domUtils.js
Labels: sync, LawyZheng

#3035 fix scraping issue
  skyvern/webeye/scraper/scraper.py
Labels: sync, LawyZheng

#3036 point anthropic back to bedrock
  skyvern/config.py
Labels: sync, wintonzheng

#3046 add webhook failure reason
  alembic/versions/2025_07_28_1606-1d0a10ae2a13_add_webhook_failure_reason.py
  skyvern/forge/agent.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/schemas/task_v2.py
  skyvern/forge/sdk/schemas/tasks.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/services/task_v2_service.py
Labels: sync, LawyZheng

#3048 Temperature fix for O-models
  skyvern/forge/sdk/api/llm/config_registry.py
Labels: sync, suchintan

#3050 robust scrolling screenshot
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#3054 Jon/sky 5741 enable take control via buttons in browser stream component
  skyvern-frontend/src/components/BrowserStream.tsx
Labels: sync, jomido

#3058 optimize scrolling screenshot logic
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#3059 parse filename from http header
  skyvern/forge/sdk/api/files.py
Labels: sync, LawyZheng

#3062 fix task v2 cancel
  skyvern/services/task_v2_service.py
Labels: sync, LawyZheng

#3066 add deleted_at column to debug_sessions table
  alembic/versions/2025_07_30_2338-bddb54c1509b_add_deleted_at_column_to_debug_sessions_.py
  skyvern/forge/sdk/db/models.py
Labels: sync, jomido

#3067 count block children in determining whether to enable debugging via b…
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/workflowEditorUtils.ts
Labels: sync, jomido

#3068 add status column to debug_sessions table
  alembic/versions/2025_07_31_1342-0ecb03206fc6_add_status_column_to_debug_sessions_.py
  skyvern/forge/sdk/db/models.py
Labels: sync, jomido

#3071 disable lmnr instrument
  skyvern/forge/sdk/trace/lmnr.py
Labels: sync, LawyZheng
