Repository Skyvern-AI/skyvern, pull requests merged in 2025-10, with the labels that each got.

#3577 skip malformed css selector
  skyvern/webeye/scraper/domUtils.js
Labels: sync, pedrohsdb

#3580 Delete workflow scripts (bust cache) when workflow definition is updated
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, wintonzheng

#3581 add ai_fallback to workflow_runs
  alembic/versions/2025_10_01_2107-d36daac4941e_add_ai_fallback_to_workflow_runs.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/runs.py
  skyvern/services/script_service.py
Labels: sync, wintonzheng

#3584 Updating Gemini flash pointers in registry and frontend to preview-09-2025
  skyvern/config.py
  skyvern/forge/sdk/api/llm/config_registry.py
Labels: sync, pedrohsdb

#3586 do not delete cache when running task v2 while workflow is being updated
  skyvern/forge/sdk/workflow/service.py
  skyvern/services/task_v2_service.py
Labels: sync, wintonzheng

#3589 fix task v2 post action script gen - update workflow definition before execution the generated block
  skyvern/services/task_v2_service.py
Labels: sync, wintonzheng

#3593 turn on run_with code and ai fallback by default for task v2
  skyvern-frontend/src/routes/tasks/create/PromptBox.tsx
  skyvern-frontend/src/routes/workflows/editor/workflowEditorUtils.ts
  skyvern-frontend/src/routes/workflows/types/workflowTypes.ts
  skyvern-frontend/src/routes/workflows/types/workflowYamlTypes.ts
  skyvern-frontend/src/store/WorkflowHasChangesStore.ts
Labels: sync, wintonzheng

#3597 fix workflow_runs.code_gen to enforce code generate only for task v2 block run
  alembic/versions/2025_10_02_2256-cce87185dbb5_add_code_gen_column_to_workflow_runs.py
  skyvern/forge/agent_functions.py
  skyvern/forge/sdk/core/skyvern_context.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/executor/async_executor.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/services/block_service.py
  skyvern/services/task_v2_service.py
  skyvern/services/workflow_service.py
Labels: sync, wintonzheng

#3601 All workflows are created with 'default' cache_key
  skyvern/schemas/workflows.py
Labels: sync, wintonzheng

#3603 generate description for cached action
  skyvern/core/script_generations/skyvern_page.py
  skyvern/forge/prompts/skyvern/generate-action-reasoning.j2
  skyvern/forge/sdk/db/client.py
  skyvern/schemas/workflows.py
Labels: sync, wintonzheng

#3605 fix task v2 block + post action code gen
  skyvern/core/script_generations/generate_script.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, wintonzheng

#3607 adding real username and pwd keys
  skyvern/forge/sdk/workflow/models/block.py
Labels: sync, pedrohsdb

#3608 add pre click back to select option handler
  skyvern/webeye/actions/handler.py
Labels: sync, wintonzheng

#3610 fix empty cache_key_value for block run cache
  skyvern/services/workflow_script_service.py
Labels: sync, wintonzheng

#3611 sanitize python func names in script gen
  skyvern/core/script_generations/generate_script.py
Labels: sync, wintonzheng

#3620 add Download Timeout to FileDownloadNode
  skyvern-frontend/src/api/types.ts
  skyvern-frontend/src/routes/workflows/editor/nodes/FileDownloadNode/FileDownloadNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/FileDownloadNode/types.ts
  skyvern-frontend/src/routes/workflows/editor/workflowEditorUtils.ts
  skyvern-frontend/src/routes/workflows/types/workflowTypes.ts
  skyvern-frontend/src/routes/workflows/types/workflowYamlTypes.ts
Labels: sync, jomido

#3626 ensure browser control buttons in debugger are always on
  skyvern-frontend/src/components/BrowserStream.tsx
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
Labels: sync, jomido

#3627 fix select for cache key in workflow run code view
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunCode.tsx
Labels: sync, jomido

#3631 render totp_identifier & totp_url real value
  skyvern/core/script_generations/skyvern_page.py
Labels: sync, wintonzheng

#3630 support openrouter qwen model
  skyvern/config.py
  skyvern/forge/sdk/api/llm/api_handler_factory.py
  skyvern/forge/sdk/api/llm/models.py
  tests/unit_tests/test_openrouter_integration.py
Labels: sync, wintonzheng

#3632 fix script run totp
  skyvern/core/script_generations/skyvern_page.py
  skyvern/webeye/actions/handler.py
Labels: sync, wintonzheng

#3633 use registered captcha solver action handler in script run
  skyvern/core/script_generations/skyvern_page.py
Labels: sync, wintonzheng

#3635 improve input handler
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#3637 Increase bitwarden timeout to 30s
  skyvern/forge/sdk/services/bitwarden.py
Labels: sync, stanislaw89

#3639 reorganize workflow updates so that we can sanely check if we need to prompt user about code cache deletion on the frontend
  skyvern/exceptions.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, jomido

#3641 add dialog for confirmation of code cache deletion
  skyvern-frontend/src/routes/workflows/editor/Workspace.tsx
  skyvern-frontend/src/store/WorkflowHasChangesStore.ts
Labels: sync, jomido
