Repository Skyvern-AI/skyvern, pull requests merged in 2025-06, with the labels that each got.

#2557 use model_name instead of name
  skyvern/config.py
  skyvern/forge/agent.py
  skyvern/forge/sdk/schemas/task_v2.py
  skyvern/forge/sdk/schemas/tasks.py
  skyvern/forge/sdk/workflow/models/workflow.py
Labels: sync

#2560 Update model selector to use O4 mini
  skyvern/config.py
Labels: kash

#2575 fix jinja runtime leak
  skyvern/forge/sdk/workflow/models/block.py
Labels: sync

#2576 fix selfhost streaming issue
  .gitignore
  skyvern/forge/sdk/executor/async_executor.py
Labels: sync

#2588 fallback gemini to gpt + use latest gemini flash 2.5 release
  skyvern/forge/sdk/api/llm/config_registry.py
Labels: sync

#2595 enhance clickable element detect
  skyvern/webeye/scraper/domUtils.js
Labels: sync

#2565 Add run lifecycle timestamps
  alembic/versions/2025_06_02_0050-add_run_timestamps.py
  scripts/test_persistent_browsers.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/schemas/task_v2.py
  skyvern/forge/sdk/schemas/tasks.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/runs.py
  skyvern/services/run_service.py
  skyvern/services/task_v2_service.py
  skyvern/services/workflow_service.py
  tests/unit_tests/__init__.py
  tests/unit_tests/test_run_timestamps.py
  tests/unit_tests/test_url_validators.py
Labels: kash

#2605 enrich local logger
  skyvern/cli/__init__.py
  skyvern/cli/commands.py
  skyvern/cli/stop_commands.py
  skyvern/client/client.py
  skyvern/forge/sdk/forge_log.py
Labels: sync

#2621 fix input interactable detect
  skyvern/webeye/scraper/domUtils.js
Labels: sync

#2641 feat: summarize failure on max retries
  skyvern/forge/agent.py
  skyvern/forge/prompts/skyvern/summarize-max-retries-reason.j2
Labels: sync

#2655 CodeGen part1 - move ActionType to it's own py file
  skyvern/forge/agent.py
  skyvern/forge/sdk/models.py
  skyvern/webeye/actions/action_types.py
  skyvern/webeye/actions/actions.py
  skyvern/webeye/actions/caching.py
  skyvern/webeye/actions/handler.py
  skyvern/webeye/actions/parse_actions.py
Labels: sync

#2662 fix timeout for svg and css LLM call
  skyvern/forge/agent_functions.py
  skyvern/forge/sdk/api/llm/api_handler_factory.py
Labels: sync

#2671 decrease svg css timeout to 30s
  skyvern/forge/agent_functions.py
Labels: sync, LawyZheng

#2677 overhual llm key override
  skyvern/forge/agent.py
  skyvern/forge/sdk/api/llm/api_handler_factory.py
  skyvern/forge/sdk/api/llm/models.py
  skyvern/services/task_v2_service.py
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#2680 fix package usage
  poetry.lock
  pyproject.toml
Labels: sync, LawyZheng

#2686 add browser session id to workflow run form
  skyvern-frontend/src/hooks/useLocalStorageFormDefault.ts
  skyvern-frontend/src/hooks/useSyncFormFieldToStorage.ts
  skyvern-frontend/src/routes/workflows/RunWorkflowForm.tsx
Labels: sync, jomido

#2694 weave browser_session_id thru ForLoopBlock
  skyvern/forge/sdk/workflow/models/block.py
Labels: sync, jomido

#2698 set url to NONE by default for generated task in loop
  skyvern/services/task_v2_service.py
Labels: sync, LawyZheng

#2699 return pbs id on workflow run endpoint
  skyvern/client/types/workflow_run_response.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/schemas/runs.py
Labels: sync, jomido

#2704 fix 1password totp
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/workflow/context_manager.py
Labels: sync, wintonzheng

#2706 vnc: persistent sessions manager update
  skyvern/exceptions.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/webeye/browser_manager.py
  skyvern/webeye/persistent_sessions_manager.py
Labels: sync, jomido

#2715 enable ui tars cua
  skyvern/forge/agent.py
Labels: sync, LawyZheng

#2716 current viewpoint screenshot and scrolling n screenshot
  alembic/versions/2025_06_14_0649-2c6b27e8e961_add_screenshot_scroll_number.py
  skyvern-frontend/src/api/types.ts
  skyvern-frontend/src/routes/tasks/create/CreateNewTaskForm.tsx
  skyvern-frontend/src/routes/tasks/create/CreateNewTaskFormPage.tsx
  skyvern-frontend/src/routes/tasks/create/PromptBox.tsx
  skyvern-frontend/src/routes/tasks/create/retry/RetryTask.tsx
  skyvern-frontend/src/routes/tasks/create/taskFormTypes.ts
  skyvern-frontend/src/routes/workflows/RunWorkflowForm.tsx
  skyvern-frontend/src/routes/workflows/WorkflowRun.tsx
  skyvern-frontend/src/routes/workflows/WorkflowRunParameters.tsx
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowEditor.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/types.ts
  skyvern-frontend/src/routes/workflows/editor/nodes/Taskv2Node/types.ts
  skyvern-frontend/src/routes/workflows/editor/workflowEditorUtils.ts
  skyvern-frontend/src/routes/workflows/types/workflowTypes.ts
  skyvern-frontend/src/routes/workflows/types/workflowYamlTypes.ts
  skyvern/constants.py
  skyvern/forge/agent.py
  skyvern/forge/sdk/core/skyvern_context.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/executor/async_executor.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/schemas/task_v2.py
  skyvern/forge/sdk/schemas/tasks.py
  skyvern/forge/sdk/workflow/models/block.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/models/yaml.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/runs.py
  skyvern/services/run_service.py
  skyvern/services/task_v2_service.py
  skyvern/services/workflow_service.py
  skyvern/webeye/browser_factory.py
  skyvern/webeye/scraper/domUtils.js
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#2721 action handler helper function - download_file_safe
  skyvern/webeye/actions/handler.py
  skyvern/webeye/actions/handler_utils.py
Labels: sync, wintonzheng

#2746 add a vnc streaming component for workflows
  skyvern-frontend/src/api/types.ts
  skyvern-frontend/src/novnc.d.ts
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunOverview.tsx
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunStreamVnc.tsx
  skyvern-frontend/src/routes/workflows/workflowRun/workflow-run-stream-vnc.css
Labels: sync, jomido

#2752 user defined browser header
  alembic/versions/2025_06_19_0740-a9fd7a08469c_add_extra_headers.py
  skyvern/forge/agent.py
  skyvern/forge/sdk/db/client.py
  skyvern/forge/sdk/db/models.py
  skyvern/forge/sdk/db/utils.py
  skyvern/forge/sdk/routes/agent_protocol.py
  skyvern/forge/sdk/schemas/task_v2.py
  skyvern/forge/sdk/schemas/tasks.py
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/models/yaml.py
  skyvern/forge/sdk/workflow/service.py
  skyvern/schemas/runs.py
  skyvern/services/task_v2_service.py
  skyvern/webeye/browser_factory.py
  skyvern/webeye/browser_manager.py
Labels: sync, LawyZheng

#2754 remove unused index on primary keys
  alembic/versions/2025_06_19_2002-2d2f165170f1_remove_unused_index_on_primary_key.py
  skyvern/forge/sdk/db/models.py
Labels: sync, wintonzheng

#2755 add artifacts_org_created_at_index for artifacts table
  alembic/versions/2025_06_19_2259-afeed80576cb_add_index_for_artifacts_table_.py
  skyvern/forge/sdk/db/models.py
Labels: sync, wintonzheng

#2761 frontend support browser header
  skyvern-frontend/src/api/types.ts
  skyvern-frontend/src/components/KeyValueInput.tsx
  skyvern-frontend/src/routes/tasks/create/CreateNewTaskForm.tsx
  skyvern-frontend/src/routes/tasks/create/CreateNewTaskFormPage.tsx
  skyvern-frontend/src/routes/tasks/create/PromptBox.tsx
  skyvern-frontend/src/routes/tasks/create/retry/RetryTask.tsx
  skyvern-frontend/src/routes/tasks/create/taskFormTypes.ts
  skyvern-frontend/src/routes/tasks/detail/TaskParameters.tsx
  skyvern-frontend/src/routes/workflows/RunWorkflowForm.tsx
  skyvern-frontend/src/routes/workflows/WorkflowRunParameters.tsx
  skyvern-frontend/src/routes/workflows/editor/FlowRenderer.tsx
  skyvern-frontend/src/routes/workflows/editor/WorkflowEditor.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/types.ts
  skyvern-frontend/src/routes/workflows/editor/workflowEditorUtils.ts
  skyvern-frontend/src/routes/workflows/types/workflowTypes.ts
  skyvern-frontend/src/routes/workflows/types/workflowYamlTypes.ts
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowPostRunParameters.tsx
  skyvern/forge/sdk/workflow/models/workflow.py
  skyvern/forge/sdk/workflow/service.py
Labels: sync, LawyZheng

#2762 fix extra headers label/explainer
  skyvern-frontend/src/routes/tasks/detail/TaskParameters.tsx
  skyvern-frontend/src/routes/workflows/editor/nodes/StartNode/StartNode.tsx
Labels: sync, jomido

#2780 parse action context before triggering the sequential click logic
  skyvern/webeye/actions/handler.py
Labels: sync, LawyZheng

#2782 WebSocket Command Channel
  skyvern-frontend/src/routes/workflows/editor/panels/WorkflowParametersPanel.tsx
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunStreamVnc.tsx
  skyvern-frontend/src/store/useClientIdStore.ts
  skyvern/forge/sdk/routes/__init__.py
  skyvern/forge/sdk/routes/streaming_auth.py
  skyvern/forge/sdk/routes/streaming_clients.py
  skyvern/forge/sdk/routes/streaming_commands.py
  skyvern/forge/sdk/routes/streaming_verify.py
  skyvern/forge/sdk/routes/streaming_vnc.py
Labels: sync, jomido

#2797 update verification code prompt
  skyvern/forge/agent.py
  skyvern/forge/prompts/skyvern/extract-action.j2
  skyvern/forge/prompts/skyvern/single-input-action.j2
Labels: sync, LawyZheng

#2798 fallback to take screenshot with animation allowed
  skyvern/webeye/utils/page.py
Labels: sync, LawyZheng

#2801 do not parse the dropped element twice
  skyvern/forge/agent_functions.py
  skyvern/forge/sdk/core/skyvern_context.py
Labels: sync, LawyZheng

#2802 Remove x-api-key from logs
  skyvern/forge/request_logging.py
Labels: sync, jomido

#2803 Add RESIDENTIAL_AU proxy support for Australia
  skyvern/client/types/proxy_location.py
  skyvern/client/types/workflow_run_request.py
  skyvern/schemas/docs/doc_strings.py
  skyvern/schemas/runs.py
Labels: sync, Prakashmaheshwaran

#2804 udated pyproject to fix typer errors
  poetry.lock
  pyproject.toml
Labels: sync, Prakashmaheshwaran

#2808 Jon/browser stream component
  skyvern-frontend/src/components/BrowserStream.tsx
  skyvern-frontend/src/components/browser-stream.css
  skyvern-frontend/src/routes/workflows/workflowRun/WorkflowRunOverview.tsx
Labels: sync, jomido

#2846 add pointer detect for h element
  skyvern/webeye/scraper/domUtils.js
Labels: sync, LawyZheng
